server:
  port: ${serverPort:8443}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

spring:
  mail:
    host: ${MLR_NOTIFICATION_EMAIL_HOST}
    port: ${MLR_NOTIFICATION_EMAIL_PORT}
    defaultEncoding: UTF-8
    protocol: smtp
  profiles:
    active: default, swagger

security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
      id: ${oauthResourceId:oauth2-resource}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}
  require-ssl: true

mlrEmailTemplateFrom: ${MLR_NOTIFICATION_EMAIL_FROM}